version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - app-data:/data/db

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/SpringControllers

volumes:
  app-data: